sbatch JETS_MIXED_FCNN_param_1.sh
sbatch JETS_MIXED_FCNN_param_2.sh
sbatch JETS_MIXED_FCNN_param_3.sh
sbatch JETS_MIXED_FCNN_param_4.sh
sbatch JETS_MIXED_FCNN_param_5.sh
sbatch JETS_MIXED_FCNN_param_6.sh
sbatch JETS_MIXED_FCNN_param_7.sh
sbatch JETS_MIXED_FCNN_param_8.sh
